name: Backend Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ai_platform_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis, mysql, pdo_mysql
        coverage: xdebug

    - name: Create .env file for testing
      working-directory: backend/laravel
      run: |
        cat > .env << 'EOF'
        APP_NAME="AI Tools Platform"
        APP_ENV=testing
        APP_KEY=
        APP_DEBUG=true
        APP_URL=http://localhost:8000

        LOG_CHANNEL=stack
        LOG_DEPRECATIONS_CHANNEL=null
        LOG_LEVEL=debug

        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_DATABASE=ai_platform_test
        DB_USERNAME=root
        DB_PASSWORD=password

        BROADCAST_DRIVER=log
        CACHE_DRIVER=redis
        FILESYSTEM_DISK=local
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=redis
        SESSION_LIFETIME=120

        REDIS_HOST=127.0.0.1
        REDIS_PASSWORD=null
        REDIS_PORT=6379

        MAIL_MAILER=smtp
        MAIL_HOST=localhost
        MAIL_PORT=1025
        MAIL_USERNAME=null
        MAIL_PASSWORD=null
        MAIL_ENCRYPTION=null
        MAIL_FROM_ADDRESS="hello@example.com"
        MAIL_FROM_NAME="AI Tools Platform"
        EOF

    - name: Install Composer dependencies
      working-directory: backend/laravel
      run: composer install --prefer-dist --no-progress

    - name: Generate application key
      working-directory: backend/laravel
      run: php artisan key:generate

    - name: Run database migrations
      working-directory: backend/laravel
      run: php artisan migrate --force

    - name: Run database seeders
      working-directory: backend/laravel
      run: php artisan db:seed --force

    - name: Run PHPUnit tests
      working-directory: backend/laravel
      run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Run PHP Code Sniffer
      working-directory: backend/laravel
      run: |
        if [ ! -f "vendor/bin/phpcs" ]; then
          composer require --dev squizlabs/php_codesniffer
        fi
        vendor/bin/phpcs --standard=PSR12 app/ --ignore=app/Http/Controllers/Controller.php

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: backend/laravel/coverage.xml
        flags: backend
        name: backend-coverage

  backend-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      working-directory: backend/laravel
      run: composer install --prefer-dist --no-progress

    - name: Run security audit
      working-directory: backend/laravel
      run: |
        composer require --dev enlightn/security-checker
        vendor/bin/security-checker security:check